"""Subclass of ConfigurationDlg, which is generated by wxFormBuilder."""

import wx
from gui.ArduinoRadioMainWindow import MainWindow
from utilities import db
from utilities.db import Band

# Implementing ConfigurationDlg
class ConfigurationDlg( MainWindow.ConfigurationDlg ):
	def __init__( self, parent ):
		MainWindow.ConfigurationDlg.__init__( self, parent )
		self.db= db.Db()
		self.db = self.db.db_view

	# Handlers for ConfigurationDlg events.
	def ConfigurationDlgOnInitDialog( self, event ):
		
		for heading in ('label','Min Freq.', 'Max Freq.', 'Unit', 'Mode'):
			self.band_list_ctrl.AppendColumn(heading, format=wx.LIST_FORMAT_CENTRE, width=wx.LIST_AUTOSIZE)
		for band in self.db.bands:
			self.band_list_ctrl.Append([band.label, 
                               band.format_frequency(band.f_min),
                               band.format_frequency(band.f_max),
                               band.units,
                               band.mode])
		self.band_list_ctrl.SetColumnWidth(0, width=wx.LIST_AUTOSIZE)
		pass

	def configuration_pageOnNotebookPageChanged( self, event ):
		# TODO: Implement configuration_pageOnNotebookPageChanged
		pass

	def band_list_ctrlOnListItemActivated( self, event ):
		# TODO: Implement m_listCtrl1OnListItemActivated
		pass

	def band_list_ctrlOnListItemSelected( self, event ):
		# TODO: Implement m_listCtrl1OnListItemSelected
		pass

	def add_band_btnOnButtonClick( self, event ):
		# TODO: Implement add_band_btnOnButtonClick
		pass

	def remove_band_btnOnButtonClick( self, event ):
		# TODO: Implement remove_band_btnOnButtonClick
		pass

	def move_band_up_btnOnButtonClick( self, event ):
		# TODO: Implement move_band_up_btnOnButtonClick
		pass

	def move_band_down_btnOnButtonClick( self, event ):
		# TODO: Implement move_band_down_btnOnButtonClick
		pass

	def ok_btnOnButtonClick( self, event ):
		self.EndModal(wx.OK)

	def cancel_btnOnButtonClick( self, event ):
		self.EndModal(wx.CANCEL)


