"""Subclass of EditBandDlg, which is generated by wxFormBuilder."""

import wx
import MainWindow
from utilities.db import Band

# Implementing EditBandDlg
class EditBandDlg( MainWindow.EditBandDlg ):
	def __init__( self, parent, band_info:Band=None ):
		MainWindow.EditBandDlg.__init__( self, parent )
		self.band_info = band
  
	def EditBandDlgOnInitDialog(self, event):
		if self.band_info is not None:
			self.band_label_txt = self.band_info.band
			self.min_freq_dbl_spin.SetValue(self.band_info.f_min)
			self.max_freq_dbl_spin.SetValue(self.band_info.f_max)
			index=self.units_choice.FindString(self.band_info.units) 
			self.units_choice.SetSelection(index)
			index=self.mode_choice.FindString(self.band_info.mode) 
			self.mode_choice.SetSelection(index)

	def ok_btnOnButtonClick(self, event):
		self.EndModal(wx.OK)

	def cancel_btnOnButtonClick(self, event):
		self.EndModal(wx.CANCEL)

